### ISSUE TITLE
namespace issue with "constants"

### ISSUE THREAD

**Issue by jimabramson** [dominicbarnes/node-constants#1]
This pkg scratches an itch I'm having right now, except that on my system (node 0.6.7), 

``` require("constants");```
actually returns an object full of operating system constant definitions.  If I manually rename the pkg (e.g. to 'const') it works, though that wouldn't be a sustainable solution for my purposes.
```

**Comment by dominicbarnes** [comment]
Interesting, I had no idea there was a global module with that name. It's been renamed to `const` in NPM. :)

**Comment by jimabramson** [comment]
works like a charm, thanks
